name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build backend
      run: docker build -t backend ./backend

    - name: Build frontend
      run: docker build -t frontend ./frontend